# 所有环境公用的配置属性
server:
  port: 8081

# actuator 显示健康详情
management:
  endpoint:
    health:
      show-details: always # 激活所有actuator所有端点
  endpoints:
    web:
      exposure:
        include: '*' # actuator 显示描述应用
info:
  app-name: spring
  author: hongweizhiyuan
  email: 403236160@qq:com

spring:
  profiles:
    active: dev

# 连字符

---
# profile=x的专用属性，也就是某个环境下的专用属性
# 开发环境
spring:
  profiles: dev

---
# profile=y的专用属性，也就是某个环境下的专用属性
# 开发环境
spring:
  profiles: prod
server:
  tomcat:
    max-threads: 300
    max-connections: 1000